name: Build

on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: set pythonpath
        run: |
          echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV
          echo "PATH=${PATH}:${HOME}/.local/bin" >> $GITHUB_ENV
      - name: Install Requirements
        run: |
          pip install .[test]
      - name: Run tests
        run: |
          pycodestyle src tests setup.py
          tox
